# Generated by Django 6.0.6 on 2026-07-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='bid',
            new_name='starting_bid',
        ),
    ]
