# Generated by Django 6.0.6 on 2026-07-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_bid_auction_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
